export const LOGIN = 'LOGIN'
export const ADD_CART = 'cart/add_cart'
export const REMOVE_CART = 'cart/remove_cart'
export const INCREMENT_CART = 'cart/increment'
export const DECREMENT_CART = 'cart/decrement'
export const REMOVE_ITEMS = 'cart/remove_items'
